%% Create ToolboxToolbox configuration for VirtualScenesAssets.

config = [ ...
    tbToolboxRecord( ...
    'name', 'MagicInputParser', ...
    'type', 'include'), ...
    tbToolboxRecord( ...
    'name', 'mexximp', ...
    'type', 'include'), ...
    tbToolboxRecord( ...
    'name', 'RenderToolbox4', ...
    'type', 'include'), ...
    tbToolboxRecord( ...
    'name', 'AssetIOToolbox', ...
    'type', 'include'), ...
    tbToolboxRecord( ...
    'name', 'VirtualScenesExampleAssets', ...
    'type', 'git', ...
    'url', 'https://github.com/RenderToolbox/VirtualScenesExampleAssets.git'), ...
    tbToolboxRecord( ...
    'name', 'VirtualScenesEngine', ...
    'type', 'git', ...
    'url', 'https://github.com/RenderToolbox/VirtualScenesEngine.git'), ...
    ];

pathHere = fileparts(mfilename('fullpath'));
configPath = fullfile(pathHere, 'vseToolboxConfig.json');
tbWriteConfig(config, 'configPath', configPath);
